apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.backend }}
  name: "{{ $.Chart.Name }}-{{ .type }}-deployment"
  namespace: {{ $.Chart.Name }}
  labels:
{{- include "common.labels" $ | indent 4 }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}
      type: {{ .type }}
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}
        type: {{ .type }}
    spec:
      containers:
        - name: "{{ $.Chart.Name }}-{{ .type }}"
          image: "{{ .image }}:{{ .version }}"
          ports:
            - containerPort: {{ .port }}
          resources:
            limits: {{ .limits | toYaml | nindent 14 }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: "{{ $.Chart.Name }}-{{ .type }}-secret"
                  key: DATABASE_URL
          livenessProbe:
            exec:
              command:
                - curl
                - --fail
                - http://localhost:3000/api
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 1
  {{- end }}
