apiVersion: v1
kind: ConfigMap
metadata:
  {{- with .Values.database }}
  name: "{{ $.Values.appName }}-{{ .type }}-init-configmap"
  namespace: {{ $.Values.namespace }}
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS "Link" (
        "id"   SERIAL NOT NULL,
        "url"  TEXT   NOT NULL,
        "hash" TEXT   NOT NULL,
        CONSTRAINT "Link_pkey" PRIMARY KEY ("id")
    );
  {{- end }}
