apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.database }}
  name: "{{ $.Values.appName }}-{{ .type }}-deployment"
  namespace: {{ $.Values.namespace }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ $.Values.appName }}
      type: {{ .type }}
  template:
    metadata:
      labels:
        app: {{ $.Values.appName }}
        type: {{ .type }}
    spec:
      containers:
        - name: "{{ $.Values.appName }}-{{ .type }}"
          image: "{{ .image }}:{{ .version }}"
          ports:
            - containerPort: {{ .port }}
          resources:
            limits: {{ .limits | toYaml | nindent 14 }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: "{{ $.Values.appName }}-{{ .type }}-secret"
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ $.Values.appName }}-{{ .type }}-secret"
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ $.Values.appName }}-{{ .type }}-secret"
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: "{{ $.Values.appName }}-{{ .type }}-data"
              mountPath: /var/lib/postgresql/data
              subPath: postgres
            - name: "{{ $.Values.appName }}-{{ .type }}-init-configmap"
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: "{{ $.Values.appName }}-{{ .type }}-data"
          persistentVolumeClaim:
            claimName: "{{ $.Values.appName }}-{{ .type }}-pvc"
        - name: "{{ $.Values.appName }}-{{ .type }}-init-script"
          configMap:
            name: "{{ $.Values.appName }}-{{ .type }}-init-configmap"
  {{- end }}