apiVersion: v1
kind: ConfigMap
metadata:
  {{- with .Values.database }}
  name: "{{ $.Chart.Name }}-{{ .type }}-init-configmap"
  namespace: {{ $.Release.Namespace }}
  labels:
{{- include "common.labels" $ | indent 4 }}
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS "Link" (
        "id"   SERIAL NOT NULL,
        "url"  TEXT   NOT NULL,
        "hash" TEXT   NOT NULL,
        CONSTRAINT "Link_pkey" PRIMARY KEY ("id")
    );
  {{- end }}
