apiVersion: v1
kind: Secret
metadata:
  {{- with .Values.database }}
  name: "{{ $.Chart.Name }}-{{ .type }}-secret"
  namespace: {{ $.Release.Namespace }}
  labels:
{{- include "common.labels" $ | indent 4 }}
  {{- end }}
type: Opaque
data:
  {{- with .Values.database }}
  POSTGRES_DB: {{ .db | b64enc }}
  POSTGRES_USER: {{ .user | b64enc }}
  POSTGRES_PASSWORD: {{ .password | b64enc }}
  {{- end }}