apiVersion: v1
kind: Secret
metadata:
  {{- with .Values.database }}
  name: "{{ $.Values.appName }}-{{ .type }}-secret"
  namespace: {{ $.Values.namespace }}
  {{- end }}
type: Opaque
data:
  {{- with .Values.database }}
  POSTGRES_DB: {{ .db | b64enc }}
  POSTGRES_USER: {{ .user | b64enc }}
  POSTGRES_PASSWORD: {{ .password | b64enc }}
  {{- end }}