apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.frontend }}
  name: "{{ $.Chart.Name }}-{{ .type }}-deployment"
  namespace: {{ $.Release.Namespace }}
  labels:
{{- include "common.labels" $ | indent 4 }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}
      type: {{ .type }}
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}
        type: {{ .type }}
    spec:
      containers:
        - name: "{{ $.Chart.Name }}-{{ .type }}"
          image: "{{ .image }}:{{ .version }}"
          ports:
            - containerPort: {{ .port }}
          resources:
            limits: {{ .limits | toYaml | nindent 14 }}
  {{- end }}