apiVersion: v1
kind: Service
metadata:
  {{- with .Values.frontend }}
  name: "{{ $.Chart.Name }}-{{ .type }}-clusterip"
  namespace: {{ $.Release.Namespace }}
  labels:
{{- include "common.labels" $ | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .port }}
      protocol: {{ .protocol }}
  selector:
    app: {{ $.Chart.Name }}
    type: {{ .type }}
  {{- end }}