apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.app.name }}-{{ .Values.app.types.frontend.name }}-deployment"
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.app.types.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      type: {{ .Values.app.types.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        type: {{ .Values.app.types.frontend.name }}
    spec:
      containers:
        - name: "{{ .Values.app.name }}-{{ .Values.app.types.frontend.name }}"
          image: "{{ .Values.app.types.frontend.image }}:{{ .Values.app.types.frontend.version }}"
          ports:
            - containerPort: {{ .Values.app.types.frontend.port }}
          resources:
            limits: {{.Values.app.types.frontend.limits | toYaml | nindent 14 }}
