apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.app }}
  name: "{{ .name }}-{{ .types.frontend.name }}-deployment"
  namespace: {{ $.Values.namespace }}
spec:
  replicas: {{ .types.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
      type: {{ .types.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
        type: {{ .types.frontend.name }}
    spec:
      containers:
        - name: "{{ .name }}-{{ .types.frontend.name }}"
          image: "{{ .types.frontend.image }}:{{ .types.frontend.version }}"
          ports:
            - containerPort: {{ .types.frontend.port }}
          resources:
            limits: {{ .types.frontend.limits | toYaml | nindent 14 }}
  {{- end }}