apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.app.name }}-{{ .Values.app.types.demo.name }}-configmap"
  namespace: {{ .Values.namespace }}
data:
  {{- if eq .Values.env "production" }}
  paymentToken: "1234"
  {{- else }}
  paymentToken: "false"
  {{- end }}
  {{- $var := .Release.Name | upper | quote }}
  var: {{ $var }}
  users: |-
    {{- range $index, $user := .Values.users }}
    {{ $user.name }}: {{ $user.role }} - {{ $index }}
    {{- end }}
    {{- range tuple "Anton" "Vasya" }}
    - {{ . }}
    {{- end }}