apiVersion: v1
kind: Secret
metadata:
  {{- with .Values.backend }}
  name: "{{ $.Values.app_name }}-{{ .type }}-secret"
  namespace: {{ $.Values.namespace }}
  {{- end }}
type: Opaque
data:
  {{- with .Values.database }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%s/%s" .user .password .hostname .port .db | b64enc | quote }}
  {{- end }}