apiVersion: v1
kind: Service
metadata:
  name: short-app-frontend-clusterip
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: short-app
    type: frontend