apiVersion: v1
kind: Service
metadata:
  name: short-app-database-clusterip
  namespace: short-app
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: short-app
    type: database