apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-app-backend-deployment
  namespace: short-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: short-app
      type: backend
  template:
    metadata:
      labels:
        app: short-app
        type: backend
    spec:
      containers:
        - name: short-app-backend
          image: antonlarichev/short-api:v1.0
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: short-app-backend-secret
                  key: DATABASE_URL
          volumeMounts:
            - name: short-app-backend-configmap
              mountPath: /etc/test
              readOnly: true
          livenessProbe:
            exec:
              command:
                - curl
                - --fail
                - http://localhost:3000/api
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 1
      volumes:
        - name: short-app-backend-configmap
          configMap:
            name: short-app-backend-configmap
